# Generated by Django 3.0.4 on 2020-03-27 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location1', models.BigIntegerField(default=0)),
                ('Location2', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session', models.UUIDField(default='b8cbed76', editable=False)),
                ('PersonOne', models.CharField(default='0', max_length=50)),
                ('PersonTwo', models.CharField(default='0', max_length=50)),
                ('LobbyCode', models.CharField(default='0', max_length=50)),
                ('Moves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Moves')),
            ],
        ),
    ]
