# Generated by Django 3.0.4 on 2020-03-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location1', models.BigIntegerField(default=0)),
                ('location2', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='1d3b7dec', editable=False, max_length=7)),
                ('playerOne', models.CharField(default='0', max_length=50)),
                ('playerTwo', models.CharField(default='0', max_length=50)),
                ('lobbyCode', models.CharField(default='0', max_length=50)),
                ('moves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Moves')),
            ],
        ),
    ]
