# Generated by Django 3.0.4 on 2020-03-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='session',
            field=models.CharField(default='111dcbc9', editable=False, max_length=7),
        ),
    ]
