# Generated by Django 3.0.4 on 2020-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200327_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='session',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='session',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
